import type { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import fs from 'fs';
import path from 'path';
import { getWorkspacePath } from './workspace.js';

interface ComponentSelection {
  provId: string;
  layer: string;
  bbox: number[];
  provenance: {
    file?: string;
    line?: number | string;
    function?: string;
    call_chain?: Array<{ file?: string; line?: number | string; function?: string }>;
    [key: string]: unknown;
  };
}

interface BuildStatus {
  lastOutput: string;
  exitCode: number | null;
  gdsPath: string | null;
  errors: string[];
  timestamp: number;
}

interface PendingCommand {
  type: 'highlightSource' | 'selectBySource';
  file: string;
  line: number;
  id: number;
}

interface IdeState {
  selectedComponents: ComponentSelection[];
  openFile: string | null;
  cursorPosition: { line: number; column: number } | null;
  buildStatus: BuildStatus | null;
  pendingQuestion: { components: ComponentSelection[]; question: string } | null;
  pendingCommands: PendingCommand[];
}

let commandId = 0;

/**
 * Write selected component provenance to disk as a markdown file.
 * This file is readable by any AI agent (claude, codex, etc.) running in the terminal.
 * Written to <workspace>/.overgds/selection.md on every selection change.
 */
function writeSelectionCache(components: ComponentSelection[]): void {
  let workspace: string;
  try {
    workspace = getWorkspacePath();
  } catch {
    return; // No workspace set yet
  }

  const cacheDir = path.join(workspace, '.overgds');
  const cacheFile = path.join(cacheDir, 'selection.md');

  try {
    fs.mkdirSync(cacheDir, { recursive: true });
  } catch {
    // Directory exists or can't be created — proceed
  }

  let content: string;

  if (components.length === 0) {
    content = '# GDS Selection\n\n_No components selected._\n\n> This file is auto-generated by overGDS Studio.\n> AI agents: read this file to understand what the user has selected in the GDS viewer.\n';
  } else {
    const lines: string[] = [
      '# GDS Selection\n',
      `> ${components.length} component(s) selected — updated ${new Date().toISOString()}`,
      '> This file is auto-generated by overGDS Studio.',
      '> AI agents: read this file to understand what the user has selected in the GDS viewer.\n',
    ];

    for (let i = 0; i < components.length; i++) {
      const c = components[i];
      const prov = c.provenance;
      lines.push(`## Component ${i + 1}`);
      lines.push(`- **Layer**: ${c.layer}`);
      lines.push(`- **BBox**: [${c.bbox.map(v => v.toFixed(4)).join(', ')}]`);

      if (prov.instance_name) lines.push(`- **Instance**: ${prov.instance_name}`);
      if (prov.file) {
        const shortFile = (prov.file as string).replace(/\\/g, '/').split('/').pop() || prov.file;
        lines.push(`- **Source**: ${shortFile}:${prov.line || '?'}`);
        lines.push(`  - Full path: \`${prov.file}\``);
      }
      if (prov.function) lines.push(`- **Function**: ${prov.function}`);
      if (prov.layer_name) lines.push(`- **GDS Layer**: ${prov.layer_name}`);

      if (prov.call_chain && (prov.call_chain as unknown[]).length > 0) {
        lines.push('- **Call chain**:');
        for (const step of prov.call_chain as Array<{ file?: string; line?: number | string; function?: string }>) {
          lines.push(`  1. ${step.function || 'unknown'} at ${step.file || '?'}:${step.line || '?'}`);
        }
      }

      // Include any extra provenance keys
      const knownKeys = new Set(['file', 'line', 'function', 'call_chain', 'instance_name', 'layer_name']);
      const extra = Object.entries(prov).filter(([k]) => !knownKeys.has(k));
      if (extra.length > 0) {
        for (const [k, v] of extra) {
          lines.push(`- **${k}**: ${v}`);
        }
      }

      lines.push('');
    }

    content = lines.join('\n');
  }

  try {
    fs.writeFileSync(cacheFile, content, 'utf-8');
  } catch (err) {
    // Non-critical — don't break selection if write fails
    console.error('Failed to write selection cache:', err);
  }
}

// In-memory IDE state — ephemeral, lives for the server's lifetime
const ideState: IdeState = {
  selectedComponents: [],
  openFile: null,
  cursorPosition: null,
  buildStatus: null,
  pendingQuestion: null,
  pendingCommands: [],
};

export async function registerStateRoutes(app: FastifyInstance) {
  // GET /api/ide-state — read current IDE state (used by MCP server)
  app.get('/api/ide-state', async () => {
    return {
      selectedComponents: ideState.selectedComponents,
      openFile: ideState.openFile,
      cursorPosition: ideState.cursorPosition,
      buildStatus: ideState.buildStatus,
      pendingQuestion: ideState.pendingQuestion,
    };
  });

  // GET /api/ide-state/commands — fetch and clear pending commands (polled by frontend)
  app.get('/api/ide-state/commands', async () => {
    const commands = ideState.pendingCommands;
    ideState.pendingCommands = [];
    return { commands };
  });

  // POST /api/ide-state — update IDE state (from frontend or MCP server)
  app.post('/api/ide-state', async (req: FastifyRequest, reply: FastifyReply) => {
    const body = req.body as {
      type: string;
      components?: ComponentSelection[];
      file?: string;
      cursor?: { line: number; column: number };
      status?: BuildStatus;
      question?: string;
      line?: number;
    };

    switch (body.type) {
      case 'selection':
        if (body.components) {
          ideState.selectedComponents = body.components;
          // Write selection to disk cache for terminal-based AI agents
          writeSelectionCache(body.components);
        }
        break;
      case 'openFile':
        ideState.openFile = body.file ?? null;
        break;
      case 'cursor':
        ideState.cursorPosition = body.cursor ?? null;
        break;
      case 'build':
        if (body.status) {
          ideState.buildStatus = body.status;
        }
        break;
      case 'askClaude':
        if (body.components && body.question) {
          ideState.pendingQuestion = {
            components: body.components,
            question: body.question,
          };
        }
        break;
      case 'highlightSource':
      case 'selectBySource':
        if (body.file && body.line) {
          ideState.pendingCommands.push({
            type: body.type,
            file: body.file,
            line: body.line,
            id: ++commandId,
          });
        }
        break;
      default:
        reply.code(400).send({ error: `Unknown state type: ${body.type}` });
        return;
    }

    reply.send({ ok: true });
  });
}
